import fs from "node:fs/promises";
import os from "node:os";
import path from "node:path";

export interface FakePiDirs {
  childPath: string;
  logPath: string;
}

export async function createFakePiChild(tmpPrefix = "subagent007-fake-pi-"): Promise<FakePiDirs> {
  const tmp = await fs.mkdtemp(path.join(os.tmpdir(), tmpPrefix));
  const childPath = path.join(tmp, "fake-pi-child.cjs");
  const logPath = path.join(tmp, "fake-pi-child.jsonl");
  await fs.writeFile(
    childPath,
    [
      "#!/usr/bin/env node",
      "const fs = require('fs');",
      "const path = require('path');",
      "const net = require('net');",
      "const crypto = require('crypto');",
      "const { spawn } = require('child_process');",
      "const request = JSON.parse(fs.readFileSync(process.argv[2], 'utf8'));",
      "const logPath = process.env.FAKE_PI_LOG_PATH;",
      "if (logPath) fs.appendFileSync(logPath, JSON.stringify({ pid: process.pid, request }) + '\\n');",
      "process.stdin.resume();",
      "process.stdin.once('end', () => {",
      "  if (process.platform === 'win32') { process.kill(process.pid, 'SIGTERM'); return; }",
      "  const absorbGracefulSignal = () => {};",
      "  process.once('SIGTERM', absorbGracefulSignal);",
      "  try {",
      "    process.kill(-process.pid, 'SIGTERM');",
      "  } catch {",
      "    process.removeListener('SIGTERM', absorbGracefulSignal);",
      "    process.kill(process.pid, 'SIGTERM');",
      "    return;",
      "  }",
      "  setTimeout(() => process.kill(-process.pid, 'SIGKILL'), 1000);",
      "});",
      "let releaseOwnerCommit;",
      "const ownerCommitRelease = new Promise((resolve) => { releaseOwnerCommit = resolve; });",
      "let ownerCommitReleased = false;",
      "const delayedEffect = request.prompt.includes('DELAYED_CONSEQUENTIAL_EFFECT') ? {",
      "  path: process.env.FAKE_PI_DELAYED_EFFECT_PATH || path.join(request.cwd, 'consequential-effect.txt'),",
      "  nonce: process.env.FAKE_PI_DELAYED_EFFECT_NONCE || 'default-delayed-effect',",
      "  delayMs: Number(process.env.FAKE_PI_DELAYED_EFFECT_DELAY_MS || '350'),",
      "  timerElapsed: false,",
      "  written: false",
      "} : null;",
      "function performDelayedEffectIfReleased() {",
      "  if (!delayedEffect || delayedEffect.written || !delayedEffect.timerElapsed || !ownerCommitReleased) return;",
      "  delayedEffect.written = true;",
      "  fs.writeFileSync(delayedEffect.path, 'effect nonce=' + delayedEffect.nonce + '\\n');",
      "  if (request.outputLastMessagePath && request.outputMode === 'final') fs.writeFileSync(request.outputLastMessagePath, 'DELAYED EFFECT DONE');",
      "  else process.stdout.write('DELAYED EFFECT DONE');",
      "  process.stdin.pause();",
      "}",
      "if (delayedEffect) {",
      "  if (logPath) fs.appendFileSync(logPath, JSON.stringify({ event: 'delayed_effect_armed', run_id: request.runId, pid: process.pid, nonce: delayedEffect.nonce, delay_ms: delayedEffect.delayMs, effect_path: delayedEffect.path, armed_at: new Date().toISOString() }) + '\\n');",
      "  setTimeout(() => { delayedEffect.timerElapsed = true; performDelayedEffectIfReleased(); }, delayedEffect.delayMs);",
      "}",
      "let ownerControlBuffer = '';",
      "process.stdin.setEncoding('utf8');",
      "process.stdin.on('data', (chunk) => {",
      "  ownerControlBuffer += chunk;",
      "  let newline;",
      "  while ((newline = ownerControlBuffer.indexOf('\\n')) >= 0) {",
      "    const line = ownerControlBuffer.slice(0, newline);",
      "    ownerControlBuffer = ownerControlBuffer.slice(newline + 1);",
      "    try {",
      "      const message = JSON.parse(line);",
      "      if (!ownerCommitReleased && message.type === 'subagent007.owner_commit_release' && message.version === 1 && Object.keys(message).length === 2) {",
      "        ownerCommitReleased = true;",
      "        performDelayedEffectIfReleased();",
      "        releaseOwnerCommit();",
      "      }",
      "    } catch {}",
      "  }",
      "});",
      "void (async () => {",
      "await ownerCommitRelease;",
      "function writeEvent(event) { process.stdout.write(JSON.stringify(event) + '\\n'); }",
      "writeEvent({ type: 'subagent007.lifecycle', event: 'child_bridge_started' });",
      "if (request.prompt.includes('DUPLICATE_CHILD_BRIDGE')) setTimeout(() => writeEvent({ type: 'subagent007.lifecycle', event: 'child_bridge_started' }), 30);",
      "function writeFinal(text) {",
      "  if (request.outputLastMessagePath && request.outputMode === 'final') fs.writeFileSync(request.outputLastMessagePath, text);",
      "  else process.stdout.write(text);",
      "  process.stdin.pause();",
      "}",
      "function redactedRequestForOutput() {",
      "  const clone = { ...request };",
      "  if (clone.recursiveControl) clone.recursiveControl = { ...clone.recursiveControl, token: '[redacted]' };",
      "  return clone;",
      "}",
      "function callRecursiveDelegate(params, callerOverride) {",
      "  const control = request.recursiveControl;",
      "  if (!control) return Promise.resolve({ status: 'rejected', kind: 'recursive_delegate_rejected', success: false, reason_code: 'recursive_control_invalid', message: 'missing recursive control' });",
      "  const id = 'fake-' + process.pid + '-' + Date.now();",
      "  const payload = {",
      "    id,",
      "    token: control.token,",
      "    method: 'delegate',",
      "    caller: callerOverride || {",
      "      parent_run_id: control.parent_run_id,",
      "      root_run_id: control.root_run_id,",
      "      recursion_depth: control.recursion_depth,",
      "      ...(control.system_skill_name ? { system_skill_name: control.system_skill_name } : {})",
      "    },",
      "    params",
      "  };",
      "  return new Promise((resolve, reject) => {",
      "    const socket = net.createConnection(control.socket_path);",
      "    let buffer = '';",
      "    socket.setEncoding('utf8');",
      "    socket.once('connect', () => socket.write(JSON.stringify(payload) + '\\n'));",
      "    socket.once('error', reject);",
      "    socket.on('data', (chunk) => {",
      "      buffer += chunk;",
      "      const index = buffer.indexOf('\\n');",
      "      if (index === -1) return;",
      "      socket.end();",
      "      const response = JSON.parse(buffer.slice(0, index));",
      "      if (response.id !== id) throw new Error('recursive response id mismatch');",
      "      resolve(response.ok ? response.result : { status: 'rejected', kind: 'recursive_delegate_rejected', success: false, error_class: 'validation_error', reason_code: response.error.reason_code, message: response.error.message });",
      "    });",
      "  });",
      "}",
      "function callRecursiveRejoin(params, callerOverride) {",
      "  const control = request.recursiveControl;",
      "  if (!control) return Promise.resolve({ status: 'rejected', kind: 'recursive_delegate_rejected', success: false, reason_code: 'recursive_control_invalid', message: 'missing recursive control' });",
      "  const id = 'fake-rejoin-' + process.pid + '-' + Date.now();",
      "  const payload = {",
      "    id,",
      "    token: control.token,",
      "    method: 'rejoin',",
      "    caller: callerOverride || {",
      "      parent_run_id: control.parent_run_id,",
      "      root_run_id: control.root_run_id,",
      "      recursion_depth: control.recursion_depth,",
      "      ...(control.system_skill_name ? { system_skill_name: control.system_skill_name } : {})",
      "    },",
      "    params",
      "  };",
      "  return new Promise((resolve, reject) => {",
      "    const socket = net.createConnection(control.socket_path);",
      "    let buffer = '';",
      "    socket.setEncoding('utf8');",
      "    socket.once('connect', () => socket.write(JSON.stringify(payload) + '\\n'));",
      "    socket.once('error', reject);",
      "    socket.on('data', (chunk) => {",
      "      buffer += chunk;",
      "      const index = buffer.indexOf('\\n');",
      "      if (index === -1) return;",
      "      socket.end();",
      "      const response = JSON.parse(buffer.slice(0, index));",
      "      if (response.id !== id) throw new Error('recursive rejoin response id mismatch');",
      "      resolve(response.ok ? response.result : { status: 'rejected', kind: 'recursive_delegate_rejected', success: false, error_class: 'validation_error', reason_code: response.error.reason_code, message: response.error.message });",
      "    });",
      "  });",
      "}",
      "function packetFinal(packet) {",
      "  return '```contract_packet_v1\\n' + JSON.stringify(packet) + '\\n```';",
      "}",
      "function sessionFileForFresh() {",
      "  if (!request.sessionDir) return null;",
      "  fs.mkdirSync(request.sessionDir, { recursive: true });",
      "  const sessionFile = path.join(request.sessionDir, 'fake-pi-session.jsonl');",
      "  fs.writeFileSync(sessionFile, JSON.stringify({ type: 'session', id: 'fake-pi-session' }) + '\\n');",
      "  return sessionFile;",
      "}",
      "if (!request.prompt.includes('OMIT_RECURSIVE_DELEGATION_RECEIPT')) writeEvent({ type: 'subagent007.recursive_delegation_confirmed', receipt: { schema_version: 1, confirmed_before_prompt: true, requested_recursive_delegation: request.requestedRecursiveDelegation == null ? null : request.requestedRecursiveDelegation, resolved_recursive_delegation: request.recursiveDelegation || 'disabled', delegate_tool_active: request.recursiveDelegation === 'enabled' && Boolean(request.recursiveControl) } });",
      "function writeInputRequest() {",
      "  const runDir = path.join(request.mailboxRoot, request.runId);",
      "  fs.mkdirSync(runDir, { recursive: true });",
      "  const requestId = request.runId + '-abcdef123456';",
      "  fs.writeFileSync(path.join(runDir, requestId + '.json'), JSON.stringify({ schema_version: 2, request_id: requestId, run_id: request.runId, session_id: null, created_at: new Date().toISOString(), question: 'Need fake input?', options: [], option_ids: [], freeform: true, max_answer_chars: 64 }) + '\\n');",
      "  writeEvent({ type: 'subagent007.input_request', request_id: requestId, question: 'Need fake input?', option_count: 0, freeform: true });",
      "  let buffer = '';",
      "  process.stdin.setEncoding('utf8');",
      "  process.stdin.on('data', (chunk) => {",
      "    buffer += chunk;",
      "    let newline;",
      "    while ((newline = buffer.indexOf('\\n')) >= 0) {",
      "      const line = buffer.slice(0, newline);",
      "      buffer = buffer.slice(newline + 1);",
      "      const message = JSON.parse(line);",
      "      if (message.type === 'subagent007.input_response' && message.request_id === requestId) {",
      "        if (request.prompt.includes('EXIT_BEFORE_ACK')) { process.exit(1); return; }",
      "        setTimeout(() => {",
      "          writeEvent({ type: 'subagent007.input_response_accepted', run_id: request.runId, request_id: requestId, response_id: message.response_id });",
      "          if (request.prompt.includes('ACK_THEN_EXIT')) { setTimeout(() => { process.stdin.pause(); process.exit(0); }, 10); return; }",
      "          setTimeout(() => { writeFinal('INPUT CONTINUED'); process.stdin.pause(); process.exit(0); }, 1000);",
      "        }, request.prompt.includes('DELAYED_ACK') ? 180 : 0);",
      "      }",
      "    }",
      "  });",
      "}",
      "let sessionFile = null;",
      "if (request.sessionMode === 'fresh' && !request.prompt.includes('NO_SESSION')) sessionFile = sessionFileForFresh();",
      "if (request.sessionMode === 'resume') sessionFile = request.sessionFile;",
      "if (sessionFile && !request.prompt.includes('OMIT_SESSION_EVENT')) writeEvent({ type: 'subagent007.session', session_id: sessionFile, session_file: sessionFile, pi_session_id: 'fake-pi-session-id' });",
      "if (!sessionFile && request.prompt.includes('EMIT_EPHEMERAL_SESSION_EVENT')) writeEvent({ type: 'subagent007.session', session_id: null, session_file: null, pi_session_id: 'fake-ephemeral-session-id' });",
      "if ((request.effectProfile || request.expectedSkillSha256) && !request.prompt.includes('OMIT_ACTIVATION_RECEIPT')) {",
      "  const activeToolNames = request.effectProfile === 'task_root_authoring_v1' ? ['read', 'write'] : request.effectProfile === 'skill_creator_authoring_v1' ? ['read', 'grep', 'find', 'ls', 'write', 'edit'] : request.effectProfile === 'researcher_bounded_v1' || request.effectProfile === 'assumption_audit_bounded_v1' ? (request.effectProfile === 'researcher_bounded_v1' ? ['read', 'grep', 'find', 'ls', 'write', 'edit', 'web_search', 'web_read', 'researchctl'] : ['read', 'grep', 'find', 'ls', 'write', 'edit', 'web_search', 'web_read', 'aj_switchboard']) : ['read', 'grep', 'find', 'ls', 'web_search', 'web_read', 'request_input'];",
      "  if (request.prompt.includes('CONFLICT_ACTIVATION_RECEIPT')) activeToolNames.push('bash');",
      "  let toolBindings = request.expectedActivationToolBindings || (request.effectProfile === 'workspace_read_only' ? [",
      "    { tool_name: 'request_input', provider_id: 'subagent007-pi/request_input', implementation_sha256: 'a'.repeat(64) },",
      "    { tool_name: 'web_read', provider_id: 'pi-search-hub@fake', implementation_sha256: 'b'.repeat(64) },",
      "    { tool_name: 'web_search', provider_id: 'pi-search-hub@fake', implementation_sha256: 'b'.repeat(64) }",
      "  ] : []);",
      "  if (request.prompt.includes('OMIT_CONTROLLER_BINDING')) toolBindings = toolBindings.slice(0, -1);",
      "  if (request.prompt.includes('MUTATE_CONTROLLER_BINDING') && toolBindings.length) toolBindings = toolBindings.map((binding, index) => index === toolBindings.length - 1 ? { ...binding, implementation_sha256: 'f'.repeat(64) } : binding);",
      "  const toolsetSha256 = request.effectProfile ? crypto.createHash('sha256').update(JSON.stringify({ profile: request.effectProfile, active_tool_names: activeToolNames, tool_bindings: toolBindings })).digest('hex') : null;",
      "  writeEvent({ type: 'subagent007.activation_confirmed', receipt: { schema_version: request.effectProfile === 'researcher_bounded_v1' ? 4 : request.expectedEffectScopeBinding ? 2 : 1, confirmed_before_prompt: true, requested_effect_profile: request.effectProfile || null, resolved_effect_profile: request.effectProfile || null, active_tool_names: request.effectProfile ? activeToolNames : [], tool_bindings: toolBindings, toolset_sha256: toolsetSha256, skill_binding: request.skillBinding || null, ...(request.expectedEffectScopeBinding ? { effect_scope_binding: request.expectedEffectScopeBinding } : {}), ...(request.effectProfile === 'researcher_bounded_v1' ? { controller_state_discovery: 'researchctl_state_paths_v1', controller_protocol: 'researchctl_strict_v2' } : {}) } });",
      "}",
      "if (request.skillSnapshotBinding && request.expectedSkillSnapshotActivationReceipt && !request.prompt.includes('OMIT_SKILL_SNAPSHOT_RECEIPT')) writeEvent({ type: 'subagent007.skill_snapshot_activation_confirmed', receipt: request.expectedSkillSnapshotActivationReceipt });",
      "if (request.systemSkill && request.expectedSystemSkillPath && !request.prompt.includes('OMIT_SYSTEM_SKILL_RECEIPT')) {",
      "  const systemSkillContent = fs.readFileSync(request.expectedSystemSkillPath, 'utf8');",
      "  const contentSha256 = crypto.createHash('sha256').update(Buffer.from(systemSkillContent, 'utf8')).digest('hex');",
      "  const systemSkillBlock = '<subagent007-system-skill>\\nName: ' + request.systemSkill + '\\nCanonical source: ' + request.expectedSystemSkillPath + '\\n\\n' + systemSkillContent + '\\n</subagent007-system-skill>';",
      "  const finalSystemPrompt = 'FAKE PI BASE SYSTEM PROMPT\\n\\n' + systemSkillBlock;",
      "  writeEvent({ type: 'subagent007.system_skill_activation_confirmed', receipt: { schema_version: 1, confirmed_before_prompt: true, system_skill_name: request.systemSkill, resolved_skill_path: request.expectedSystemSkillPath, content_sha256: contentSha256, final_system_prompt_sha256: crypto.createHash('sha256').update(finalSystemPrompt).digest('hex'), system_skill_content_occurrences: 1, final_system_prompt_ends_with_system_skill: true, placement: 'after_all_other_before_agent_start_handlers', observation_scope: 'pi_system_prompt_after_before_agent_start_not_provider_payload_or_model_obedience' } });",
      "}",
      "if (!request.prompt.includes('OMIT_PROMPT_SUBMITTED')) writeEvent({ type: 'subagent007.lifecycle', event: 'child_prompt_submitted' });",
      "if (request.prompt.includes('RESEARCH_COMPLETE_JOB')) {",
      "  const stateRoot = path.join(request.cwd, '.subagent007', 'researcher_bounded_v1');",
      "  fs.mkdirSync(stateRoot, { recursive: true });",
      "  fs.writeFileSync(path.join(stateRoot, 'job.json'), JSON.stringify({ state: 'complete', dispatch_protocol: 'research_web_dispatch_v1' }) + '\\n', 'utf8');",
      "}",
      "if (request.prompt.includes('TIMEOUT_SPAWN_CHILD')) {",
      "  process.on('SIGTERM', () => {});",
      "  const child = spawn(process.execPath, ['-e', \"process.on('SIGTERM', () => {}); setInterval(() => {}, 1000);\"], { stdio: 'ignore' });",
      "  fs.writeFileSync(path.join(request.cwd, 'child.pid'), String(child.pid));",
      "  process.stdout.write('TIMEOUT START\\n' + 'A'.repeat(200000) + '\\n');",
      "  setInterval(() => {}, 1000);",
      "} else if (request.prompt.includes('TIMEOUT_RAW_TEXT')) {",
      "  process.stdout.write('RAW CHILD TEXT BEFORE TIMEOUT\\n');",
      "  setInterval(() => {}, 1000);",
      "} else if (request.prompt.includes('TIMEOUT_ASSISTANT_EVENT')) {",
      "  writeEvent({ type: 'message_end', message: { role: 'assistant', content: [{ type: 'text', text: 'PUBLIC PARTIAL ASSISTANT' }] } });",
      "  setInterval(() => {}, 1000);",
      "} else if (request.prompt.includes('TIMEOUT_WARNING_EVENT')) {",
      "  writeEvent({ type: 'subagent007.warning', message: 'PUBLIC WARNING' });",
      "  setInterval(() => {}, 1000);",
      "} else if (request.prompt.includes('TIMEOUT_ERROR_EVENT')) {",
      "  writeEvent({ type: 'subagent007.error', error: 'PUBLIC ERROR' });",
      "  setInterval(() => {}, 1000);",
      "} else if (request.prompt.includes('TIMEOUT_FINAL_MESSAGE')) {",
      "  writeFinal('PUBLIC FINAL BEFORE TIMEOUT');",
      "  setInterval(() => {}, 1000);",
      "} else if (request.prompt.includes('HEARTBEAT_INPUT_WAIT')) {",
      "  setTimeout(writeInputRequest, 800);",
      "} else if (request.prompt.includes('RECURSIVE_LONG_OUTPUT')) {",
      "  setTimeout(() => writeFinal('RECURSIVE LONG START\\n' + 'x'.repeat(1200) + '\\nRECURSIVE LONG END'), 520);",
      "} else if (request.prompt.includes('HEARTBEAT_LONG_WAIT')) {",
      "  setTimeout(() => writeFinal('HEARTBEAT LONG DONE'), 520);",
      "} else if (request.prompt.includes('HEARTBEAT_SLEEP')) {",
      "  setTimeout(() => writeFinal('HEARTBEAT DONE'), 160);",
      "} else if (request.prompt.includes('DELAYED_CONSEQUENTIAL_EFFECT')) {",
      "  // The nonce-bound timer was armed before release; its effect is release-gated.",
      "} else if (request.prompt.includes('AUTHORING_WRITE_OUTPUT')) {",
      "  const output = request.expectedEffectScopeBinding.writable_scope.paths[0];",
      "  fs.mkdirSync(path.dirname(output), { recursive: true });",
      "  fs.writeFileSync(output, '# Skill\\n');",
      "  writeFinal('AUTHORING OUTPUT WRITTEN');",
      "} else if (request.prompt.includes('AUTHORING_EXTRA_OUTPUT')) {",
      "  fs.writeFileSync(path.join(request.cwd, 'undeclared-output.txt'), 'extra\\n');",
      "  writeFinal('AUTHORING EXTRA WRITTEN');",
      "} else if (request.prompt.includes('AUTHORING_SWAP_INPUT_LEAF')) {",
      "  const input = path.join(request.cwd, 'input.txt');",
      "  const replacement = path.join(request.cwd, '.replacement-input');",
      "  fs.writeFileSync(replacement, fs.readFileSync(input));",
      "  fs.renameSync(replacement, input);",
      "  fs.mkdirSync(path.dirname(request.expectedEffectScopeBinding.writable_scope.paths[0]), { recursive: true });",
      "  fs.writeFileSync(request.expectedEffectScopeBinding.writable_scope.paths[0], '# Skill\\n');",
      "  writeFinal('AUTHORING INPUT SWAPPED');",
      "} else if (request.prompt.includes('AUTHORING_SWAP_INPUT_PARENT')) {",
      "  const inputDir = path.join(request.cwd, 'inputs');",
      "  const moved = path.join(request.cwd, 'inputs-original');",
      "  const data = fs.readFileSync(path.join(inputDir, 'request.json'));",
      "  fs.renameSync(inputDir, moved);",
      "  fs.mkdirSync(inputDir);",
      "  fs.writeFileSync(path.join(inputDir, 'request.json'), data);",
      "  fs.mkdirSync(path.dirname(request.expectedEffectScopeBinding.writable_scope.paths[0]), { recursive: true });",
      "  fs.writeFileSync(request.expectedEffectScopeBinding.writable_scope.paths[0], '# Skill\\n');",
      "  writeFinal('AUTHORING INPUT PARENT SWAPPED');",
      "} else if (request.prompt.includes('AUTHORING_MUTATE_THEN_FAIL')) {",
      "  fs.writeFileSync(path.join(request.cwd, 'input.txt'), 'mutated before failure\\n');",
      "  process.stderr.write('AUTHORING MUTATION THEN FAILURE\\n');",
      "  process.exit(42);",
      "} else if (request.prompt.includes('AUTHORING_MUTATE_THEN_CANCEL_WAIT')) {",
      "  fs.writeFileSync(path.join(request.cwd, 'input.txt'), 'mutated before cancellation\\n');",
      "  setInterval(() => {}, 1000);",
      "} else if (request.prompt.includes('MUTATE_SKILL_SNAPSHOT_AFTER_ACTIVATION')) {",
      "  fs.chmodSync(request.expectedSkillSnapshotActivationReceipt.resolved_skill_path, 0o644);",
      "  fs.writeFileSync(request.expectedSkillSnapshotActivationReceipt.resolved_skill_path, '# mutated snapshot\\n');",
      "  writeFinal('SNAPSHOT MUTATED');",
      "} else if (request.prompt.includes('SIDE_EFFECT_THEN_FINAL')) {",
      "  fs.writeFileSync(path.join(request.cwd, 'side-effect.txt'), 'side effect complete\\n');",
      "  writeEvent({ type: 'message_end', message: { role: 'assistant', content: [{ type: 'text', text: 'PUBLIC SIDE EFFECT PROGRESS' }] } });",
      "  writeFinal('SIDE EFFECT FINAL');",
      "} else if (request.prompt.includes('CLEAN_EXIT_NO_FINAL')) {",
      "  fs.writeFileSync(path.join(request.cwd, 'side-effect-no-final.txt'), 'side effect complete\\n');",
      "  process.stdin.pause();",
      "} else if (request.prompt.includes('CANCEL_WAIT')) {",
      "  setInterval(() => {}, 1000);",
      "} else if (request.prompt.includes('REQUEST_INPUT_WAIT') || request.prompt.includes('REQUEST_INPUT_DELAYED_ACK') || request.prompt.includes('REQUEST_INPUT_ACK_THEN_EXIT') || request.prompt.includes('REQUEST_INPUT_EXIT_BEFORE_ACK')) {",
      "  writeInputRequest();",
      "} else if (request.prompt.includes('FAIL_EXIT')) {",
      "  process.stderr.write('FAKE PI FAILURE\\n');",
      "  process.exit(42);",
      "} else if (request.prompt.includes('USAGE_LIMIT_WITH_RESET')) {",
      "  process.stderr.write('[subagent007 error] Codex error: ' + JSON.stringify({",
      "    type: 'error',",
      "    error: { type: 'usage_limit_reached', message: 'The usage limit has been reached', plan_type: 'pro', resets_at: 1782491143, resets_in_seconds: 205140 },",
      "    status_code: 429,",
      "    headers: {",
      "      'Retry-After': '60',",
      "      'X-Codex-Plan-Type': 'pro',",
      "      'X-Codex-Primary-Used-Percent': '26',",
      "      'X-Codex-Secondary-Used-Percent': '100',",
      "      'X-Codex-Primary-Reset-After-Seconds': '3600',",
      "      'X-Codex-Secondary-Reset-After-Seconds': '205140'",
      "    }",
      "  }) + '\\n');",
      "  process.exit(1);",
      "} else if (request.prompt.includes('USAGE_LIMIT_REACHED')) {",
      "  process.stderr.write('[subagent007 error] Codex error: ' + JSON.stringify({ type: 'error', error: { type: 'usage_limit_reached', message: 'The usage limit has been reached' }, status_code: 429 }) + '\\n');",
      "  process.exit(1);",
      "} else if (request.prompt.includes('SIGNAL_TERM')) {",
      "  setImmediate(() => process.kill(process.pid, 'SIGTERM'));",
      "} else if (request.prompt.includes('ECHO_REQUEST')) {",
      "  writeFinal(JSON.stringify(redactedRequestForOutput()));",
      "} else if (request.prompt.includes('RECURSIVE_DELEGATE_FAST') || request.prompt.includes('RECURSIVE_DELEGATE_DEPTH_LIMIT') || request.prompt.includes('RECURSIVE_DELEGATE_WAIT')) {",
      "  callRecursiveDelegate({ prompt: request.prompt.includes('RECURSIVE_DELEGATE_WAIT') ? 'HEARTBEAT_LONG_WAIT' : 'FAST', cwd: request.cwd, wait_ms: request.prompt.includes('RECURSIVE_DELEGATE_WAIT') ? 0 : 1000 }).then((result) => {",
      "    writeFinal(JSON.stringify({ delegated: result }));",
      "  }).catch((error) => {",
      "    process.stderr.write('FAKE RECURSIVE DELEGATE FAILURE: ' + (error && error.stack ? error.stack : String(error)) + '\\n');",
      "    process.exitCode = 1;",
      "  });",
      "} else if (request.prompt.includes('RECURSIVE_REJOIN_CHILD')) {",
      "  callRecursiveDelegate({ prompt: 'RECURSIVE_LONG_OUTPUT', cwd: request.cwd, wait_ms: 2000 }).then((delegated) => {",
      "    return callRecursiveRejoin({ run_id: delegated.run_id, wait_ms: 0 }).then((rejoined) => writeFinal(JSON.stringify({ delegated, rejoined })));",
      "  }).catch((error) => {",
      "    process.stderr.write('FAKE RECURSIVE REJOIN FAILURE: ' + (error && error.stack ? error.stack : String(error)) + '\\n');",
      "    process.exitCode = 1;",
      "  });",
      "} else if (request.prompt.includes('RECURSIVE_REJOIN_ROOT')) {",
      "  callRecursiveDelegate({ prompt: 'RECURSIVE_REJOIN_CHILD', cwd: request.cwd, wait_ms: 0 }).then((initial) => {",
      "    return callRecursiveRejoin({ run_id: initial.run_id, wait_ms: 3000 }).then((rejoined) => writeFinal(JSON.stringify({ initial, rejoined })));",
      "  }).catch((error) => {",
      "    process.stderr.write('FAKE RECURSIVE REJOIN FAILURE: ' + (error && error.stack ? error.stack : String(error)) + '\\n');",
      "    process.exitCode = 1;",
      "  });",
      "} else if (request.prompt.includes('RECURSIVE_REJOIN_FOREIGN')) {",
      "  callRecursiveRejoin({ run_id: request.runId, wait_ms: 0 }).then((rejoined) => writeFinal(JSON.stringify({ rejoined }))).catch((error) => {",
      "    process.stderr.write('FAKE RECURSIVE REJOIN FAILURE: ' + (error && error.stack ? error.stack : String(error)) + '\\n');",
      "    process.exitCode = 1;",
      "  });",
      "} else if (request.prompt.includes('RECURSIVE_DELEGATE_FORGED_PARENT')) {",
      "  callRecursiveDelegate({ prompt: 'FAST', cwd: request.cwd, wait_ms: 1000 }, {",
      "    parent_run_id: request.runId + '-forged',",
      "    root_run_id: request.runId,",
      "    recursion_depth: 0",
      "  }).then((result) => {",
      "    writeFinal(JSON.stringify({ delegated: result }));",
      "  }).catch((error) => {",
      "    process.stderr.write('FAKE RECURSIVE DELEGATE FAILURE: ' + (error && error.stack ? error.stack : String(error)) + '\\n');",
      "    process.exitCode = 1;",
      "  });",
      "} else if (request.prompt.includes('MANY_PUBLIC_EVENTS')) {",
      "  const publicEventCount = Number(/MANY_PUBLIC_EVENTS(?::(\\d+))?/.exec(request.prompt)?.[1] || 30);",
      "  for (let index = 0; index < publicEventCount; index += 1) writeEvent({ type: 'subagent007.warning', message: 'PUBLIC EVENT ' + index });",
      "  writeFinal('MANY PUBLIC EVENTS DONE count=' + publicEventCount);",
      "} else if (request.prompt.includes('RAW_THINKING_TRANSCRIPT')) {",
      "  writeEvent({ type: 'message_end', message: { role: 'user', content: [{ type: 'text', text: 'user prompt' }] } });",
      "  writeEvent({ type: 'message_update', assistantMessageEvent: { type: 'thinking_delta', delta: 'SECRET_THINKING_SHOULD_NOT_LEAK' } });",
      "  writeEvent({ type: 'message_end', message: { role: 'assistant', content: [{ type: 'text', text: 'PUBLIC ASSISTANT TEXT' }] } });",
      "  process.stdin.pause();",
      "} else if (request.prompt.includes('TERMINAL_CAP_FINAL')) {",
      "  writeFinal('x'.repeat((1024 * 1024) + 1));",
      "} else if (request.prompt.includes('TERMINAL_CAP_TRANSCRIPT')) {",
      "  for (let index = 0; index < 17; index += 1) writeEvent({ type: 'message_end', message: { role: 'assistant', content: [{ type: 'text', text: 'x'.repeat(64 * 1024) }] } });",
      "  process.stdin.pause();",
      "} else if (request.prompt.includes('LARGE_TRANSCRIPT')) {",
      "  writeEvent({ type: 'message_end', message: { role: 'assistant', content: [{ type: 'text', text: 'LARGE PUBLIC ' + 'x'.repeat(300 * 1024) }] } });",
      "  process.stdin.pause();",
      "} else if (request.prompt.includes('PACKET_INCONCLUSIVE')) {",
      "  writeFinal(packetFinal({ verdict: 'inconclusive', summary: 'not ready', findings: [], blockers: ['needs evidence'], next_step: 'repair' }));",
      "} else if (request.prompt.includes('PACKET_NEEDS_REPAIR')) {",
      "  writeFinal(packetFinal({ verdict: 'needs_repair', summary: 'repair needed', findings: [], blockers: [], next_step: 'repair' }));",
      "} else if (request.prompt.includes('PACKET_BLOCKED')) {",
      "  writeFinal(packetFinal({ verdict: 'blocked', summary: 'blocked', findings: [], blockers: ['blocked by dependency'], next_step: 'unblock' }));",
      "} else if (request.prompt.includes('PACKET_READY_WITH_BLOCKER')) {",
      "  writeFinal(packetFinal({ verdict: 'ready', summary: 'ready but blocked', findings: [], blockers: ['blocker remains'], next_step: 'clear blocker' }));",
      "} else if (request.prompt.includes('PACKET_VALID_WITH_CLOSURE')) {",
      "  writeFinal(packetFinal({",
      "    verdict: 'ready',",
      "    summary: 'ok with closure',",
      "    findings: [],",
      "    blockers: [],",
      "    next_step: 'done',",
      "    closure: {",
      "      canonical_closure_source: 'tests/helpers/fakePiChild.ts',",
      "      artifact_roles: [{ path: 'tests/helpers/fakePiChild.ts', role: 'fake packet producer' }],",
      "      validation: ['closure shape parsed'],",
      "      claim_ceiling: 'fake child packet only'",
      "    }",
      "  }));",
      "} else if (request.prompt.includes('PACKET_INVALID_CLOSURE_SHAPE')) {",
      "  writeFinal(packetFinal({",
      "    verdict: 'ready',",
      "    summary: 'bad closure shape',",
      "    findings: [],",
      "    blockers: [],",
      "    next_step: 'repair closure',",
      "    closure: {",
      "      canonical_closure_source: 'tests/helpers/fakePiChild.ts',",
      "      artifact_roles: { 'tests/helpers/fakePiChild.ts': 'fake packet producer' },",
      "      validation: 'closure shape parsed',",
      "      claim_ceiling: 'fake child packet only'",
      "    }",
      "  }));",
      "} else {",
      "  writeFinal(request.prompt.includes('PACKET_VALID') ? packetFinal({ verdict: 'ready', summary: 'ok', findings: [], blockers: [], next_step: 'done' }) : 'FAST FINAL');",
      "}",
      "})().catch((error) => { process.stderr.write(String(error && error.stack ? error.stack : error) + '\\n'); process.exitCode = 1; });",
      "",
    ].join("\n"),
  );
  await fs.writeFile(path.join(tmp, "boundedController.js"), "export const fixed = true;\n", "utf8");
  await fs.chmod(childPath, 0o755);
  return { childPath, logPath };
}
