import fs from "node:fs/promises";
import os from "node:os";
import path from "node:path";

export interface FakePiDirs {
  childPath: string;
  logPath: string;
}

export async function createFakePiChild(tmpPrefix = "subagent007-fake-pi-"): Promise<FakePiDirs> {
  const tmp = await fs.mkdtemp(path.join(os.tmpdir(), tmpPrefix));
  const childPath = path.join(tmp, "fake-pi-child.cjs");
  const logPath = path.join(tmp, "fake-pi-child.jsonl");
  await fs.writeFile(
    childPath,
    [
      "#!/usr/bin/env node",
      "const fs = require('fs');",
      "const path = require('path');",
      "const { spawn } = require('child_process');",
      "const request = JSON.parse(fs.readFileSync(process.argv[2], 'utf8'));",
      "const logPath = process.env.FAKE_PI_LOG_PATH;",
      "if (logPath) fs.appendFileSync(logPath, JSON.stringify({ request }) + '\\n');",
      "function writeEvent(event) { process.stdout.write(JSON.stringify(event) + '\\n'); }",
      "writeEvent({ type: 'subagent007.lifecycle', event: 'child_bridge_started' });",
      "function writeFinal(text) {",
      "  if (request.outputLastMessagePath && request.outputMode === 'final') fs.writeFileSync(request.outputLastMessagePath, text);",
      "  else process.stdout.write(text);",
      "}",
      "function packetFinal(packet) {",
      "  return '```contract_packet_v1\\n' + JSON.stringify(packet) + '\\n```';",
      "}",
      "function sessionFileForFresh() {",
      "  if (!request.sessionDir) return null;",
      "  fs.mkdirSync(request.sessionDir, { recursive: true });",
      "  const sessionFile = path.join(request.sessionDir, 'fake-pi-session.jsonl');",
      "  fs.writeFileSync(sessionFile, JSON.stringify({ type: 'session', id: 'fake-pi-session' }) + '\\n');",
      "  return sessionFile;",
      "}",
      "function writeInputRequest() {",
      "  const runDir = path.join(request.mailboxRoot, request.runId);",
      "  fs.mkdirSync(runDir, { recursive: true });",
      "  const requestId = request.runId + '-abcdef123456';",
      "  fs.writeFileSync(path.join(runDir, requestId + '.json'), JSON.stringify({ schema_version: 1, request_id: requestId, run_id: request.runId, session_id: null, created_at: new Date().toISOString(), question: 'Need fake input?', options: [], freeform: true }) + '\\n');",
      "  writeEvent({ type: 'subagent007.input_request', request_id: requestId, question: 'Need fake input?', option_count: 0, freeform: true });",
      "  setInterval(() => {}, 1000);",
      "}",
      "let sessionFile = null;",
      "if (request.sessionMode === 'fresh' && !request.prompt.includes('NO_SESSION')) sessionFile = sessionFileForFresh();",
      "if (request.sessionMode === 'resume') sessionFile = request.sessionFile;",
      "if (sessionFile && !request.prompt.includes('OMIT_SESSION_EVENT')) writeEvent({ type: 'subagent007.session', session_id: sessionFile, session_file: sessionFile, pi_session_id: 'fake-pi-session-id' });",
      "writeEvent({ type: 'subagent007.lifecycle', event: 'child_prompt_submitted' });",
      "if (request.prompt.includes('TIMEOUT_SPAWN_CHILD')) {",
      "  process.on('SIGTERM', () => {});",
      "  const child = spawn(process.execPath, ['-e', \"process.on('SIGTERM', () => {}); setInterval(() => {}, 1000);\"], { stdio: 'ignore' });",
      "  fs.writeFileSync(path.join(request.cwd, 'child.pid'), String(child.pid));",
      "  process.stdout.write('TIMEOUT START\\n' + 'A'.repeat(200000) + '\\n');",
      "  setInterval(() => {}, 1000);",
      "} else if (request.prompt.includes('TIMEOUT_RAW_TEXT')) {",
      "  process.stdout.write('RAW CHILD TEXT BEFORE TIMEOUT\\n');",
      "  setInterval(() => {}, 1000);",
      "} else if (request.prompt.includes('TIMEOUT_ASSISTANT_EVENT')) {",
      "  writeEvent({ type: 'message_end', message: { role: 'assistant', content: [{ type: 'text', text: 'PUBLIC PARTIAL ASSISTANT' }] } });",
      "  setInterval(() => {}, 1000);",
      "} else if (request.prompt.includes('TIMEOUT_WARNING_EVENT')) {",
      "  writeEvent({ type: 'subagent007.warning', message: 'PUBLIC WARNING' });",
      "  setInterval(() => {}, 1000);",
      "} else if (request.prompt.includes('TIMEOUT_ERROR_EVENT')) {",
      "  writeEvent({ type: 'subagent007.error', error: 'PUBLIC ERROR' });",
      "  setInterval(() => {}, 1000);",
      "} else if (request.prompt.includes('TIMEOUT_FINAL_MESSAGE')) {",
      "  writeFinal('PUBLIC FINAL BEFORE TIMEOUT');",
      "  setInterval(() => {}, 1000);",
      "} else if (request.prompt.includes('HEARTBEAT_LONG_WAIT')) {",
      "  setTimeout(() => writeFinal('HEARTBEAT LONG DONE'), 520);",
      "} else if (request.prompt.includes('HEARTBEAT_SLEEP')) {",
      "  setTimeout(() => writeFinal('HEARTBEAT DONE'), 160);",
      "} else if (request.prompt.includes('CANCEL_WAIT')) {",
      "  setInterval(() => {}, 1000);",
      "} else if (request.prompt.includes('REQUEST_INPUT_WAIT')) {",
      "  writeInputRequest();",
      "} else if (request.prompt.includes('FAIL_EXIT')) {",
      "  process.stderr.write('FAKE PI FAILURE\\n');",
      "  process.exit(42);",
      "} else if (request.prompt.includes('ECHO_REQUEST')) {",
      "  writeFinal(JSON.stringify(request));",
      "} else if (request.prompt.includes('RAW_THINKING_TRANSCRIPT')) {",
      "  writeEvent({ type: 'message_end', message: { role: 'user', content: [{ type: 'text', text: 'user prompt' }] } });",
      "  writeEvent({ type: 'message_update', assistantMessageEvent: { type: 'thinking_delta', delta: 'SECRET_THINKING_SHOULD_NOT_LEAK' } });",
      "  writeEvent({ type: 'message_end', message: { role: 'assistant', content: [{ type: 'text', text: 'PUBLIC ASSISTANT TEXT' }] } });",
      "} else if (request.prompt.includes('PACKET_INCONCLUSIVE')) {",
      "  writeFinal(packetFinal({ verdict: 'inconclusive', summary: 'not ready', findings: [], blockers: ['needs evidence'], next_step: 'repair' }));",
      "} else if (request.prompt.includes('PACKET_NEEDS_REPAIR')) {",
      "  writeFinal(packetFinal({ verdict: 'needs_repair', summary: 'repair needed', findings: [], blockers: [], next_step: 'repair' }));",
      "} else if (request.prompt.includes('PACKET_BLOCKED')) {",
      "  writeFinal(packetFinal({ verdict: 'blocked', summary: 'blocked', findings: [], blockers: ['blocked by dependency'], next_step: 'unblock' }));",
      "} else if (request.prompt.includes('PACKET_READY_WITH_BLOCKER')) {",
      "  writeFinal(packetFinal({ verdict: 'ready', summary: 'ready but blocked', findings: [], blockers: ['blocker remains'], next_step: 'clear blocker' }));",
      "} else if (request.prompt.includes('PACKET_VALID_WITH_CLOSURE')) {",
      "  writeFinal(packetFinal({",
      "    verdict: 'ready',",
      "    summary: 'ok with closure',",
      "    findings: [],",
      "    blockers: [],",
      "    next_step: 'done',",
      "    closure: {",
      "      canonical_closure_source: 'tests/helpers/fakePiChild.ts',",
      "      artifact_roles: [{ path: 'tests/helpers/fakePiChild.ts', role: 'fake packet producer' }],",
      "      validation: ['closure shape parsed'],",
      "      claim_ceiling: 'fake child packet only'",
      "    }",
      "  }));",
      "} else if (request.prompt.includes('PACKET_INVALID_CLOSURE_SHAPE')) {",
      "  writeFinal(packetFinal({",
      "    verdict: 'ready',",
      "    summary: 'bad closure shape',",
      "    findings: [],",
      "    blockers: [],",
      "    next_step: 'repair closure',",
      "    closure: {",
      "      canonical_closure_source: 'tests/helpers/fakePiChild.ts',",
      "      artifact_roles: { 'tests/helpers/fakePiChild.ts': 'fake packet producer' },",
      "      validation: 'closure shape parsed',",
      "      claim_ceiling: 'fake child packet only'",
      "    }",
      "  }));",
      "} else {",
      "  writeFinal(request.prompt.includes('PACKET_VALID') ? packetFinal({ verdict: 'ready', summary: 'ok', findings: [], blockers: [], next_step: 'done' }) : 'FAST FINAL');",
      "}",
      "",
    ].join("\n"),
  );
  await fs.chmod(childPath, 0o755);
  return { childPath, logPath };
}
