import fs from "node:fs/promises";
import os from "node:os";
import path from "node:path";

export interface FakePiDirs {
  childPath: string;
  logPath: string;
}

export async function createFakePiChild(tmpPrefix = "subagent007-fake-pi-"): Promise<FakePiDirs> {
  const tmp = await fs.mkdtemp(path.join(os.tmpdir(), tmpPrefix));
  const childPath = path.join(tmp, "fake-pi-child.cjs");
  const logPath = path.join(tmp, "fake-pi-child.jsonl");
  await fs.writeFile(
    childPath,
    [
      "#!/usr/bin/env node",
      "const fs = require('fs');",
      "const path = require('path');",
      "const net = require('net');",
      "const { spawn } = require('child_process');",
      "const request = JSON.parse(fs.readFileSync(process.argv[2], 'utf8'));",
      "const logPath = process.env.FAKE_PI_LOG_PATH;",
      "if (logPath) fs.appendFileSync(logPath, JSON.stringify({ request }) + '\\n');",
      "function writeEvent(event) { process.stdout.write(JSON.stringify(event) + '\\n'); }",
      "writeEvent({ type: 'subagent007.lifecycle', event: 'child_bridge_started' });",
      "function writeFinal(text) {",
      "  if (request.outputLastMessagePath && request.outputMode === 'final') fs.writeFileSync(request.outputLastMessagePath, text);",
      "  else process.stdout.write(text);",
      "}",
      "function redactedRequestForOutput() {",
      "  const clone = { ...request };",
      "  if (clone.recursiveControl) clone.recursiveControl = { ...clone.recursiveControl, token: '[redacted]' };",
      "  return clone;",
      "}",
      "function callRecursiveDelegate(params, callerOverride) {",
      "  const control = request.recursiveControl;",
      "  if (!control) return Promise.resolve({ status: 'rejected', kind: 'recursive_delegate_rejected', success: false, reason_code: 'recursive_control_invalid', message: 'missing recursive control' });",
      "  const id = 'fake-' + process.pid + '-' + Date.now();",
      "  const payload = {",
      "    id,",
      "    token: control.token,",
      "    method: 'delegate',",
      "    caller: callerOverride || {",
      "      parent_run_id: control.parent_run_id,",
      "      root_run_id: control.root_run_id,",
      "      recursion_depth: control.recursion_depth",
      "    },",
      "    params",
      "  };",
      "  return new Promise((resolve, reject) => {",
      "    const socket = net.createConnection(control.socket_path);",
      "    let buffer = '';",
      "    socket.setEncoding('utf8');",
      "    socket.once('connect', () => socket.write(JSON.stringify(payload) + '\\n'));",
      "    socket.once('error', reject);",
      "    socket.on('data', (chunk) => {",
      "      buffer += chunk;",
      "      const index = buffer.indexOf('\\n');",
      "      if (index === -1) return;",
      "      socket.end();",
      "      const response = JSON.parse(buffer.slice(0, index));",
      "      if (response.id !== id) throw new Error('recursive response id mismatch');",
      "      resolve(response.ok ? response.result : { status: 'rejected', kind: 'recursive_delegate_rejected', success: false, error_class: 'validation_error', reason_code: response.error.reason_code, message: response.error.message });",
      "    });",
      "  });",
      "}",
      "function packetFinal(packet) {",
      "  return '```contract_packet_v1\\n' + JSON.stringify(packet) + '\\n```';",
      "}",
      "function sessionFileForFresh() {",
      "  if (!request.sessionDir) return null;",
      "  fs.mkdirSync(request.sessionDir, { recursive: true });",
      "  const sessionFile = path.join(request.sessionDir, 'fake-pi-session.jsonl');",
      "  fs.writeFileSync(sessionFile, JSON.stringify({ type: 'session', id: 'fake-pi-session' }) + '\\n');",
      "  return sessionFile;",
      "}",
      "function writeInputRequest() {",
      "  const runDir = path.join(request.mailboxRoot, request.runId);",
      "  fs.mkdirSync(runDir, { recursive: true });",
      "  const requestId = request.runId + '-abcdef123456';",
      "  fs.writeFileSync(path.join(runDir, requestId + '.json'), JSON.stringify({ schema_version: 2, request_id: requestId, run_id: request.runId, session_id: null, created_at: new Date().toISOString(), question: 'Need fake input?', options: [], option_ids: [], freeform: true, max_answer_chars: 64 }) + '\\n');",
      "  writeEvent({ type: 'subagent007.input_request', request_id: requestId, question: 'Need fake input?', option_count: 0, freeform: true });",
      "  let buffer = '';",
      "  process.stdin.setEncoding('utf8');",
      "  process.stdin.on('data', (chunk) => {",
      "    buffer += chunk;",
      "    let newline;",
      "    while ((newline = buffer.indexOf('\\n')) >= 0) {",
      "      const line = buffer.slice(0, newline);",
      "      buffer = buffer.slice(newline + 1);",
      "      const message = JSON.parse(line);",
      "      if (message.type === 'subagent007.input_response' && message.request_id === requestId) {",
      "        if (request.prompt.includes('EXIT_BEFORE_ACK')) { process.exit(1); return; }",
      "        setTimeout(() => {",
      "          writeEvent({ type: 'subagent007.input_response_accepted', run_id: request.runId, request_id: requestId, response_id: message.response_id });",
      "          if (request.prompt.includes('ACK_THEN_EXIT')) { setTimeout(() => { process.stdin.pause(); process.exit(0); }, 10); return; }",
      "          setTimeout(() => { writeFinal('INPUT CONTINUED'); process.stdin.pause(); process.exit(0); }, 1000);",
      "        }, request.prompt.includes('DELAYED_ACK') ? 180 : 0);",
      "      }",
      "    }",
      "  });",
      "}",
      "let sessionFile = null;",
      "if (request.sessionMode === 'fresh' && !request.prompt.includes('NO_SESSION')) sessionFile = sessionFileForFresh();",
      "if (request.sessionMode === 'resume') sessionFile = request.sessionFile;",
      "if (sessionFile && !request.prompt.includes('OMIT_SESSION_EVENT')) writeEvent({ type: 'subagent007.session', session_id: sessionFile, session_file: sessionFile, pi_session_id: 'fake-pi-session-id' });",
      "if (!sessionFile && request.prompt.includes('EMIT_EPHEMERAL_SESSION_EVENT')) writeEvent({ type: 'subagent007.session', session_id: null, session_file: null, pi_session_id: 'fake-ephemeral-session-id' });",
      "if (!request.prompt.includes('OMIT_PROMPT_SUBMITTED')) writeEvent({ type: 'subagent007.lifecycle', event: 'child_prompt_submitted' });",
      "if (request.prompt.includes('TIMEOUT_SPAWN_CHILD')) {",
      "  process.on('SIGTERM', () => {});",
      "  const child = spawn(process.execPath, ['-e', \"process.on('SIGTERM', () => {}); setInterval(() => {}, 1000);\"], { stdio: 'ignore' });",
      "  fs.writeFileSync(path.join(request.cwd, 'child.pid'), String(child.pid));",
      "  process.stdout.write('TIMEOUT START\\n' + 'A'.repeat(200000) + '\\n');",
      "  setInterval(() => {}, 1000);",
      "} else if (request.prompt.includes('TIMEOUT_RAW_TEXT')) {",
      "  process.stdout.write('RAW CHILD TEXT BEFORE TIMEOUT\\n');",
      "  setInterval(() => {}, 1000);",
      "} else if (request.prompt.includes('TIMEOUT_ASSISTANT_EVENT')) {",
      "  writeEvent({ type: 'message_end', message: { role: 'assistant', content: [{ type: 'text', text: 'PUBLIC PARTIAL ASSISTANT' }] } });",
      "  setInterval(() => {}, 1000);",
      "} else if (request.prompt.includes('TIMEOUT_WARNING_EVENT')) {",
      "  writeEvent({ type: 'subagent007.warning', message: 'PUBLIC WARNING' });",
      "  setInterval(() => {}, 1000);",
      "} else if (request.prompt.includes('TIMEOUT_ERROR_EVENT')) {",
      "  writeEvent({ type: 'subagent007.error', error: 'PUBLIC ERROR' });",
      "  setInterval(() => {}, 1000);",
      "} else if (request.prompt.includes('TIMEOUT_FINAL_MESSAGE')) {",
      "  writeFinal('PUBLIC FINAL BEFORE TIMEOUT');",
      "  setInterval(() => {}, 1000);",
      "} else if (request.prompt.includes('HEARTBEAT_LONG_WAIT')) {",
      "  setTimeout(() => writeFinal('HEARTBEAT LONG DONE'), 520);",
      "} else if (request.prompt.includes('HEARTBEAT_SLEEP')) {",
      "  setTimeout(() => writeFinal('HEARTBEAT DONE'), 160);",
      "} else if (request.prompt.includes('SIDE_EFFECT_THEN_FINAL')) {",
      "  fs.writeFileSync(path.join(request.cwd, 'side-effect.txt'), 'side effect complete\\n');",
      "  writeEvent({ type: 'message_end', message: { role: 'assistant', content: [{ type: 'text', text: 'PUBLIC SIDE EFFECT PROGRESS' }] } });",
      "  writeFinal('SIDE EFFECT FINAL');",
      "} else if (request.prompt.includes('CLEAN_EXIT_NO_FINAL')) {",
      "  fs.writeFileSync(path.join(request.cwd, 'side-effect-no-final.txt'), 'side effect complete\\n');",
      "} else if (request.prompt.includes('CANCEL_WAIT')) {",
      "  setInterval(() => {}, 1000);",
      "} else if (request.prompt.includes('REQUEST_INPUT_WAIT') || request.prompt.includes('REQUEST_INPUT_DELAYED_ACK') || request.prompt.includes('REQUEST_INPUT_ACK_THEN_EXIT') || request.prompt.includes('REQUEST_INPUT_EXIT_BEFORE_ACK')) {",
      "  writeInputRequest();",
      "} else if (request.prompt.includes('FAIL_EXIT')) {",
      "  process.stderr.write('FAKE PI FAILURE\\n');",
      "  process.exit(42);",
      "} else if (request.prompt.includes('USAGE_LIMIT_WITH_RESET')) {",
      "  process.stderr.write('[subagent007 error] Codex error: ' + JSON.stringify({",
      "    type: 'error',",
      "    error: { type: 'usage_limit_reached', message: 'The usage limit has been reached', plan_type: 'pro', resets_at: 1782491143, resets_in_seconds: 205140 },",
      "    status_code: 429,",
      "    headers: {",
      "      'Retry-After': '60',",
      "      'X-Codex-Plan-Type': 'pro',",
      "      'X-Codex-Primary-Used-Percent': '26',",
      "      'X-Codex-Secondary-Used-Percent': '100',",
      "      'X-Codex-Primary-Reset-After-Seconds': '3600',",
      "      'X-Codex-Secondary-Reset-After-Seconds': '205140'",
      "    }",
      "  }) + '\\n');",
      "  process.exit(1);",
      "} else if (request.prompt.includes('USAGE_LIMIT_REACHED')) {",
      "  process.stderr.write('[subagent007 error] Codex error: ' + JSON.stringify({ type: 'error', error: { type: 'usage_limit_reached', message: 'The usage limit has been reached' }, status_code: 429 }) + '\\n');",
      "  process.exit(1);",
      "} else if (request.prompt.includes('SIGNAL_TERM')) {",
      "  setImmediate(() => process.kill(process.pid, 'SIGTERM'));",
      "} else if (request.prompt.includes('ECHO_REQUEST')) {",
      "  writeFinal(JSON.stringify(redactedRequestForOutput()));",
      "} else if (request.prompt.includes('RECURSIVE_DELEGATE_FAST') || request.prompt.includes('RECURSIVE_DELEGATE_DEPTH_LIMIT')) {",
      "  callRecursiveDelegate({ prompt: 'FAST', cwd: request.cwd, wait_ms: 1000 }).then((result) => {",
      "    writeFinal(JSON.stringify({ delegated: result }));",
      "  }).catch((error) => {",
      "    process.stderr.write('FAKE RECURSIVE DELEGATE FAILURE: ' + (error && error.stack ? error.stack : String(error)) + '\\n');",
      "    process.exitCode = 1;",
      "  });",
      "} else if (request.prompt.includes('RECURSIVE_DELEGATE_FORGED_PARENT')) {",
      "  callRecursiveDelegate({ prompt: 'FAST', cwd: request.cwd, wait_ms: 1000 }, {",
      "    parent_run_id: request.runId + '-forged',",
      "    root_run_id: request.runId,",
      "    recursion_depth: 0",
      "  }).then((result) => {",
      "    writeFinal(JSON.stringify({ delegated: result }));",
      "  }).catch((error) => {",
      "    process.stderr.write('FAKE RECURSIVE DELEGATE FAILURE: ' + (error && error.stack ? error.stack : String(error)) + '\\n');",
      "    process.exitCode = 1;",
      "  });",
      "} else if (request.prompt.includes('RAW_THINKING_TRANSCRIPT')) {",
      "  writeEvent({ type: 'message_end', message: { role: 'user', content: [{ type: 'text', text: 'user prompt' }] } });",
      "  writeEvent({ type: 'message_update', assistantMessageEvent: { type: 'thinking_delta', delta: 'SECRET_THINKING_SHOULD_NOT_LEAK' } });",
      "  writeEvent({ type: 'message_end', message: { role: 'assistant', content: [{ type: 'text', text: 'PUBLIC ASSISTANT TEXT' }] } });",
      "} else if (request.prompt.includes('PACKET_INCONCLUSIVE')) {",
      "  writeFinal(packetFinal({ verdict: 'inconclusive', summary: 'not ready', findings: [], blockers: ['needs evidence'], next_step: 'repair' }));",
      "} else if (request.prompt.includes('PACKET_NEEDS_REPAIR')) {",
      "  writeFinal(packetFinal({ verdict: 'needs_repair', summary: 'repair needed', findings: [], blockers: [], next_step: 'repair' }));",
      "} else if (request.prompt.includes('PACKET_BLOCKED')) {",
      "  writeFinal(packetFinal({ verdict: 'blocked', summary: 'blocked', findings: [], blockers: ['blocked by dependency'], next_step: 'unblock' }));",
      "} else if (request.prompt.includes('PACKET_READY_WITH_BLOCKER')) {",
      "  writeFinal(packetFinal({ verdict: 'ready', summary: 'ready but blocked', findings: [], blockers: ['blocker remains'], next_step: 'clear blocker' }));",
      "} else if (request.prompt.includes('PACKET_VALID_WITH_CLOSURE')) {",
      "  writeFinal(packetFinal({",
      "    verdict: 'ready',",
      "    summary: 'ok with closure',",
      "    findings: [],",
      "    blockers: [],",
      "    next_step: 'done',",
      "    closure: {",
      "      canonical_closure_source: 'tests/helpers/fakePiChild.ts',",
      "      artifact_roles: [{ path: 'tests/helpers/fakePiChild.ts', role: 'fake packet producer' }],",
      "      validation: ['closure shape parsed'],",
      "      claim_ceiling: 'fake child packet only'",
      "    }",
      "  }));",
      "} else if (request.prompt.includes('PACKET_INVALID_CLOSURE_SHAPE')) {",
      "  writeFinal(packetFinal({",
      "    verdict: 'ready',",
      "    summary: 'bad closure shape',",
      "    findings: [],",
      "    blockers: [],",
      "    next_step: 'repair closure',",
      "    closure: {",
      "      canonical_closure_source: 'tests/helpers/fakePiChild.ts',",
      "      artifact_roles: { 'tests/helpers/fakePiChild.ts': 'fake packet producer' },",
      "      validation: 'closure shape parsed',",
      "      claim_ceiling: 'fake child packet only'",
      "    }",
      "  }));",
      "} else {",
      "  writeFinal(request.prompt.includes('PACKET_VALID') ? packetFinal({ verdict: 'ready', summary: 'ok', findings: [], blockers: [], next_step: 'done' }) : 'FAST FINAL');",
      "}",
      "",
    ].join("\n"),
  );
  await fs.chmod(childPath, 0o755);
  return { childPath, logPath };
}
